export const SET_ALBUMS = "SET_ALBUMS";
export const SET_SELECTED_ALBUM = "SET_SELECTED_ALBUM";
export const SET_SELECTED_PHOTO = "SET_SELECTED_PHOTO";
export const SET_SORT_BY = "SET_SORT_BY";
export const SET_LOADING = "SET_LOADING";
export const SET_REFRESHING = "SET_REFRESHING";